apiVersion: v1
kind: Service

metadata:
  name: service-a
  namespace: service-simple-app


spec:
  type: NodePort
  selector:
    app: service-a
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 7000
    nodePort: 30001
